; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200

lib_deps =
    https://github.com/LemurDaniel/ESP32__MiniWebServer-Framework.git

board_build.filesystem = littlefs
board_build.include_files_txt =
    data/web/index.html
    data/web/main.css
    

[env:ESP32-S3-remote]
board = esp32-s3-devkitc-1

upload_protocol = custom # This token is useless for you
upload_command = curl -H "Authorization: 23a5eac2cc5f59694c08161b0b2bcf6daa2e3afe209531454a23f7f3ff714de9" -X POST --data-binary @$SOURCE http://esp32web.fritz.box/upload/code

[env:ESP32-S3-dev]
board = esp32-s3-devkitc-1

upload_protocol = custom # This token is useless for you
upload_command = curl -H "Authorization: 86c84eb140a37bba5ad694e128a3d4e3ade811a690028e89cc6e4e0c3e967ff2" -X POST --data-binary @$SOURCE http://dev.fritz.box/upload/code


[env:ESP32-WROOM-32]
board = az-delivery-devkit-v4

[env:freenove_esp32_wrover]
board = freenove_esp32_wrover